european_countries = [
    "Albania",
    "Andorra",
    "Armenia",
    "Austria",
    "Azerbaijan",
    "Belarus",
    "Belgium",
    "Bosnia and Herzegovina",
    "Bulgaria",
    "Croatia",
    "Cyprus",
    "Czech Republic",
    "Denmark",
    "Estonia",
    "Finland",
    "France",
    "Georgia",
    "Germany",
    "Greece",
    "Hungary",
    "Iceland",
    "Ireland",
    "Italy",
    "Kosovo",
    "Latvia",
    "Liechtenstein",
    "Lithuania",
    "Luxembourg",
    "Malta",
    "Moldova",
    "Monaco",
    "Montenegro",
    "Netherlands",
    "North Macedonia",
    "Norway",
    "Poland",
    "Portugal",
    "Romania",
    "San Marino",
    "Serbia",
    "Slovakia",
    "Slovenia",
    "Spain",
    "Sweden",
    "Switzerland",
    "Turkey",
    "Ukraine",
    "United Kingdom",
    "Vatican City"
]

european_cities = [
    "London",
    "Paris",
    "Berlin",
    "Madrid",
    "Rome",
    "Amsterdam",
    "Vienna",
    "Lisbon",
    "Barcelona",
    "Budapest",
    "Warsaw",
    "Prague",
    "Valencia",
    "Istanbul"
    # "Dublin",
    # "Oslo",
    # "Helsinki",
    # "Copenhagen",
    # "Bucharest",
    # "Zurich",
    # "Munich",
    # "Lyon",
    # "Valencia",
    # "Frankfurt",
    # "Porto",
    # "Milan",
    # "Hamburg",
    # "Sofia",
    # "Edinburgh",
    # "Glasgow",
    # "Krakow",
    # "Seville",
    # "Stuttgart",
    # "Cologne",
    # "Düsseldorf",
    # "Antwerp",
    # "Nuremberg",
    # "Turin",
    # "Bilbao",
    # "Marseille",
    # "Riga",
    # "Thessaloniki",
    # "Bremen",
    # "Hanover",
    # "Palermo",
    # "Rotterdam",
    # "Liverpool",
    # "Gothenburg",
    # "Poznań",
    # "Murcia",
    # "Wrocław",
    # "Palma de Mallorca",
    # "Málaga",
    # "Genoa",
    # "Nottingham",
    # "Sheffield",
    # "Leeds",
    # "Dresden",
    # "Bristol",
    # "Utrecht",
    # "Cardiff",
    # "The Hague",
    # "Zagreb",
    # "Tallinn",
    # "Bratislava",
    # "Vilnius",
    # "Ljubljana",
    # "Gdańsk",
    # "Groningen",
    # "Cork",
    # "Newcastle upon Tyne",
    # "Aberdeen",
    # "Dresden",
    # "Ghent",
    # "Leipzig"
]

countries_dict = {country: country for country in european_countries}
cities_dict = {city: city for city in european_cities}